### ISSUE TITLE
You should specify the release version of your pod dependency in your pod spec

### ISSUE THREAD

**Issue by ben46** [clayallsopp/HybridKit-iOS#5]
First of all, thank you for the amazing project. When I install from pod, I found building failed. Then I realize you haven't specify the version of the dependency you added in your project. You should specify it in your pod spec file.

**Comment by clayallsopp** [comment]
Sorry about that, I guess CocoaPods has changed that restrictions since we released it.

I've pushed version 0.0.2 to CocoaPods: https://github.com/CocoaPods/Specs/blob/master/Specs/HybridKit/0.0.2/HybridKit.podspec.json

Try that out and let me know if there are any problems!
